package com.halove.po;

import java.util.Date;

public class UserToken {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.USER_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.ACCESS_TOKEN
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.REFRESH_TOKEN
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private String refreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.EXPIRE_TIME
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.CREATE_TIME
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.update_time
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.CLIENT_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private Long clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.DEVICE_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private Long deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_token.JPUSH_ALIAS
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    private String jpushAlias;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.ID
     *
     * @return the value of user_token.ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.ID
     *
     * @param id the value for user_token.ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.USER_ID
     *
     * @return the value of user_token.USER_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.USER_ID
     *
     * @param userId the value for user_token.USER_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.ACCESS_TOKEN
     *
     * @return the value of user_token.ACCESS_TOKEN
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.ACCESS_TOKEN
     *
     * @param accessToken the value for user_token.ACCESS_TOKEN
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.REFRESH_TOKEN
     *
     * @return the value of user_token.REFRESH_TOKEN
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public String getRefreshToken() {
        return refreshToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.REFRESH_TOKEN
     *
     * @param refreshToken the value for user_token.REFRESH_TOKEN
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken == null ? null : refreshToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.EXPIRE_TIME
     *
     * @return the value of user_token.EXPIRE_TIME
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.EXPIRE_TIME
     *
     * @param expireTime the value for user_token.EXPIRE_TIME
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.CREATE_TIME
     *
     * @return the value of user_token.CREATE_TIME
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.CREATE_TIME
     *
     * @param createTime the value for user_token.CREATE_TIME
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.update_time
     *
     * @return the value of user_token.update_time
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.update_time
     *
     * @param updateTime the value for user_token.update_time
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.CLIENT_ID
     *
     * @return the value of user_token.CLIENT_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.CLIENT_ID
     *
     * @param clientId the value for user_token.CLIENT_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.DEVICE_ID
     *
     * @return the value of user_token.DEVICE_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public Long getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.DEVICE_ID
     *
     * @param deviceId the value for user_token.DEVICE_ID
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_token.JPUSH_ALIAS
     *
     * @return the value of user_token.JPUSH_ALIAS
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public String getJpushAlias() {
        return jpushAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_token.JPUSH_ALIAS
     *
     * @param jpushAlias the value for user_token.JPUSH_ALIAS
     *
     * @mbg.generated Mon Aug 13 14:22:21 CST 2018
     */
    public void setJpushAlias(String jpushAlias) {
        this.jpushAlias = jpushAlias == null ? null : jpushAlias.trim();
    }
}